# Site wide configuration

title:            Hannah Barudin
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Hannah Barudin
  avatar: bio-photo.jpg
  bio: "Developer, theater person, generally useful person."
  email: "hbarudin@gmail.com"
  disqus-shortname: #username
  twitter: "HannahBarudin"
  facebook: #username
  google:
    plus: #username
    analytics: "UA-19406884-1"
    verify: "NAxMNKegEbDlJUBHDzlZGZNcoOfnd9gFewZ4Gj6yZKE"
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: "hbarudin"
  stackoverflow: "1582581"
  linkedin: "hannah-barudin-5ba88815"
  xing: #username
  instagram: "theatergirl62"
  lastfm: #username
  tumblr: "theatergirl62"
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: "hbarudin"
  devto: "hbarudin"

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
